### PR TITLE
First stab at upgrading to Mongoid 6.x and Rails 5.

### PR DESCRIPTION
**Pull request by aeberlin**
@did,

First stab at a mongoid 6.x and rails 5.x update, slowly working through things necessary for rails 5 on locomotive. Also, sorted out a few deprecation warnings that were clogging up the logs.

```
Finished in 10.93 seconds (files took 2.57 seconds to load)
362 examples, 2 failures

Failed examples:

rspec ./spec/integration/localize_spec.rb:141 # CustomFields::Localize retrieve a post in the locale of the content should not be nil
rspec ./spec/integration/localize_spec.rb:143 # CustomFields::Localize retrieve a post in the locale of the content url
```

### CODE REVIEW

**Comment by aeberlin** [comment]
It could be a lookup issue and it not using the current `::Mongoid::Fields::I18n.locale`?

**Comment by aeberlin** [comment]
`@blog.posts.where('url.fr' => '/bonjour-le-monde').first` does find the `subject`, so it may be a deeper issue related to the scope finders operate in.

**Comment by aeberlin** [comment]
Calling `model.foo.where(...)` does not hit `Localized#lookup`, while `.find(...)` does.

**Comment by b264** [comment]
Is this still active?

**Comment by did** [comment]
@b264. @aeberlin did an amazing job (thanks btw @aeberlin ;-)). It's my job now to take over the rest of the upgrade. It's not an easy and quick task. I hope to get time during the summer to work on it.

**Comment by did** [comment]
Finally, it took me a couple of years to tackle this :-) 
The master branch now works with Mongoid 7.5 and MongoDB 6 (both on Ruby 2.7.x and 3.0.x)
a huge thanks @aeberlin for your work!

**Pull request closed without merging**
